id: I4337C4F2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T23:31:42+00:00'
last_modified: '2022-06-08T08:07:40.289748+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS88136
  title: བོད་ལུགས་སྨན་རྩིས་སྐོར་གྱི་དཔྱད་རྩོམ་མེས་པོའི་ཞལ་རྒྱུན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    E324:
      image_group_id: I1GS88139
      title: ''
      total_pages: 330
      order: 1
      base_file: E324.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
