id: P008235
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS88136
  title: བོད་ལུགས་སྨན་རྩིས་སྐོར་གྱི་དཔྱད་རྩོམ་མེས་པོའི་ཞལ་རྒྱུན
  author: ''
  volumes:
    4109471a513540b5b795ca37b6dd9ba0:
      image_group_id: I1GS88139
      title: ''
      volume_number: 1
      total_pages: 330
      base_file: v001.txt
